name: Main

on:
  push:
    branches-ignore:
    - artifacts
    tags-ignore:
    - v*

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 0

    - name: 'Composer'
      uses: php-actions/composer@v6
      with:
        php_version: 7.4

    - name: 'Generate code'
      uses: php-actions/composer@v6
      with:
        php_version: 7.4
        command: generate

    - name: 'Push to artifacts branch'
      if: success() && startsWith(github.ref, 'refs/tags/source/v')
      run: |
        git config --global user.name 'Tarik02'
        git config --global user.email 'Tarik02@users.noreply.github.com'
        if [[ -z $(git ls-remote --heads origin artifacts) ]]; then
          git checkout --orphan artifacts
        else
          git fetch origin artifacts
          git reset origin/artifacts
          git checkout artifacts
        fi
        git rm -r --cached .
        sed -i 's/\/src/\/generator/' .gitignore
        git add .
        git commit -m "deploy \"$(git rev-parse HEAD)\""
        git push -u origin artifacts

    - name: 'Create a tag'
      if: success() && startsWith(github.ref, 'refs/tags/source/v')
      run: |
        GITHUB_REF="${{ github.ref }}"
        git tag ${GITHUB_REF#refs/tags/source/}
        git push --tags
